name: Workflows Sprocket Lint

on: [push]

jobs:
    sprocket_lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Rust
          uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
            toolchain: nightly
        - name: Install sprocket
          run: |
            cargo install sprocket
        - name: Run sprocket
          uses: stjudecloud/sprocket-action@v0.1.0
          with:
            lint: true