name: Workflows Sprocket Lint

on: [push]

jobs:
    sprocket_lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run sprocket
          uses: stjude-rust-labs/sprocket-action@v0.2.1
          with:
            lint: true
            exclude-paths:
              - template