name: Workflows Sprocket Lint

on: [push]

jobs:
    sprocket_lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Run sprocket
          uses: adthrasher/sprocket-action@main
          with:
            lint: true
            exclude-patterns: template,cellranger,scrnaseq
            deny-warnings: true
            deny-notes: true
            except: ContainerValue,TrailingComma
