name: Workflows Sprocket Lint

on: [push]

jobs:
    sprocket_lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Run sprocket
          uses: stjude-rust-labs/sprocket-action@v0.5.0-beta
          with:
            lint: true
            exclude-patterns: template
            deny-warnings: true
            deny-notes: true
            except: ContainerValue,TrailingComma
